# Generated by Django 5.2.8 on 2025-11-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetscards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='static/images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
