# Generated by Django 5.2.8 on 2025-12-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetscards',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/'),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
