# Generated by Django 5.2.8 on 2025-12-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0002_alter_projetscards_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetscards',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
