# Generated by Django 5.2.8 on 2025-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0003_alter_projetscards_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetscards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
